- name: copy action files
  copy:
    src: "{{ item }}"
    dest: "/etc/fail2ban/action.d/{{ item | basename }}"
    owner: root
    group: root
    mode: 0644
  with_fileglob: "{{ fail2ban_actiond_path }}*.conf"
  notify: restart fail2ban
  tags:
    - configuration
    - fail2ban
    - fail2ban-actions

- name: copy action templates
  template:
    src: "{{ item }}"
    dest: "/etc/fail2ban/action.d/{{ item | basename | regex_replace('\\.j2$', '') }}"
    owner: root
    group: root
    mode: 0644
  with_fileglob: "{{ fail2ban_actiond_path }}*.j2"
  notify: restart fail2ban
  tags:
    - configuration
    - fail2ban
    - fail2ban-actions
